const COMMON_LEDGERS = [
  "Purchase", "Sales", "Purchase Accounts", "Sales Accounts",
  "Professional Charges", "Office Expenses", "Rent Expenses",
  "Electricity Expenses", "Telephone Expenses", "Travel Expenses",
  "Food Expenses", "Fixed Assets", "Freight Expenses", "Bank Charges",
  "Interest Expenses", "Insurance Expenses", "Repairs & Maintenance",
  "Salary Expenses", "Software Expenses", "Legal Expenses",
  "Audit Expenses", "Advertisement Expenses", "Commission Expenses",
  "Printing & Stationery", "Postage & Courier", "Carriage Inwards",
  "Carriage Outwards", "Packing Expenses", "Labour Charges",
  "Job Work Charges", "Consulting Fees", "Management Fees",
  "Royalty Expenses", "Training Expenses", "Recruitment Expenses",
  "Membership & Subscription", "Donations", "Charity Expenses",
  "Miscellaneous Expenses", "Suspense", "Round Off",
  "TDS Payable", "GST Input CGST", "GST Input SGST", "GST Input IGST",
  "GST Output CGST", "GST Output SGST", "GST Output IGST",
  "TCS Payable", "Wages Payable", "Salary Payable",
  "Interest Payable", "Rent Payable", "Electricity Payable",
  "Outstanding Expenses", "Prepaid Expenses",
  "Capital Account", "Drawings", "Bank OD", "Cash in Hand",
  "Bank (HDFC)", "Bank (ICICI)", "Bank (SBI)", "Bank (Axis)",
  "Loans & Advances", "Security Deposits", "Advances to Suppliers",
  "Sundry Debtors", "Sundry Creditors",
  "Stock-in-Hand", "Opening Stock", "Closing Stock",
  "Purchase Returns", "Sales Returns", "Discount Allowed",
  "Discount Received", "Bad Debts", "Provision for Bad Debts",
  "Investments", "Interest Income", "Other Income",
  "Dividend Income", "Rent Income", "Commission Income",
];

export default COMMON_LEDGERS;
