"""ValidationPipeline — orchestrates all validators into one scored report.

No user should ever click "Validate". Every generation runs this automatically.
"""

from dataclasses import dataclass, field
from typing import Optional

from schemas import StandardizedInvoice
from xml_generator import TallyXmlGenerator
from validators.base import ValidationResult, ValidationScore
from validators.accounting_validator import AccountingValidator
from validators.xml_validator import XMLValidator
from validators.round_trip import RoundTripValidator
from validators.tally_simulator import TallySimulator


@dataclass
class ValidationReport:
    """Production-ready validation report for an invoice."""

    invoice_number: str = ""
    voucher_type: str = ""
    accounting_score: float = 100.0
    gst_score: float = 100.0
    xml_score: float = 100.0
    masters_score: float = 100.0
    total_score: float = 100.0
    passed: bool = True
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    blocking_errors: list[str] = field(default_factory=list)
    ready_for_tally: bool = True
    checks: list[dict] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "invoice_number": self.invoice_number,
            "voucher_type": self.voucher_type,
            "scores": {
                "accounting": self.accounting_score,
                "gst": self.gst_score,
                "xml": self.xml_score,
                "masters": self.masters_score,
                "total": self.total_score,
            },
            "passed": self.passed,
            "ready_for_tally": self.ready_for_tally,
            "error_count": len(self.errors),
            "warning_count": len(self.warnings),
            "errors": self.errors[:10],
            "warnings": self.warnings[:10],
            "blocking_errors": self.blocking_errors[:5],
            "checks": self.checks[:50],
        }

    def to_human_report(self) -> str:
        lines = [
            f"Invoice #{self.invoice_number}",
            f"Voucher Type: {self.voucher_type}",
            "",
            "Invoice Health",
            f"  Accounting: {self.accounting_score:.0f}%",
            f"  GST:        {self.gst_score:.0f}%",
            f"  XML:        {self.xml_score:.0f}%",
            f"  Masters:    {self.masters_score:.0f}%",
            f"  ───────────────────",
            f"  Total:      {self.total_score:.0f}%",
            "",
            f"  Warnings:   {len(self.warnings)}",
            f"  Errors:     {len(self.errors)}",
            "",
            f"  Ready for Tally: {'YES' if self.ready_for_tally else 'NO'}",
        ]
        if self.warnings:
            lines.append("")
            lines.append("Warnings:")
            for w in self.warnings[:5]:
                lines.append(f"  ⚠ {w}")
        if self.errors:
            lines.append("")
            lines.append("Errors:")
            for e in self.errors[:5]:
                lines.append(f"  ✘ {e}")
        lines.append("")
        lines.append(f"Generated by InvoSync — Validation Pipeline v1.0")
        return "\n".join(lines)


class ValidationPipeline:
    """One function to validate everything before import.

    Usage:
        pipeline = ValidationPipeline(generator)
        report = pipeline.run(invoice, xml_str)
        report.to_human_report()  # CA-friendly string
        report.to_dict()          # API-friendly JSON
    """

    def __init__(self, generator: Optional[TallyXmlGenerator] = None):
        self.generator = generator
        self.accounting = AccountingValidator()
        self.xml_validator = XMLValidator()
        self.round_trip = RoundTripValidator()
        self.tally_sim = TallySimulator()

    def run(
        self,
        invoice: StandardizedInvoice,
        xml_str: Optional[str] = None,
    ) -> ValidationReport:
        """Run the full validation pipeline.

        Args:
            invoice: The StandardizedInvoice to validate.
            xml_str: Optional pre-generated XML. If None, uses self.generator.

        Returns:
            ValidationReport with scores, errors, warnings, and readiness.
        """
        report = ValidationReport(
            invoice_number=invoice.invoice_number,
            voucher_type=invoice.voucher_type.value if invoice.voucher_type else "",
        )

        # ── Step 1: Accounting Validator ────────────────────────── #
        acct_result = self.accounting.validate(invoice)
        self._merge_result(report, acct_result, "accounting")

        # ── Step 2: Extract category scores ─────────────────────── #
        acct_score = ValidationScore.from_validation(acct_result)
        report.total_score = acct_score.score
        report.accounting_score = acct_score.score

        # Per-category breakdown
        gst_checks = [c for c in acct_result.checks if c.category == "gst"]
        if gst_checks:
            gst_result = ValidationResult()
            gst_result.checks = gst_checks
            gst_result.passed = all(c.passed for c in gst_checks if c.severity == "error")
            gst_score = ValidationScore.from_validation(gst_result)
            report.gst_score = gst_score.score if gst_score.score < 100 else 100.0

        # ── Step 3: XML validation ──────────────────────────────── #
        if xml_str or self.generator:
            if not xml_str:
                xml_str = self.generator.generate(invoice)
            xml_result = self.xml_validator.validate(xml_str)
            self._merge_result(report, xml_result, "xml")

            xml_score = ValidationScore.from_validation(xml_result)
            report.xml_score = xml_score.score if xml_score.score < 100 else 100.0

            # Masters sub-score
            masters_checks = [c for c in xml_result.checks if c.category == "masters"]
            if masters_checks:
                m_result = ValidationResult()
                m_result.checks = masters_checks
                m_result.passed = all(c.passed for c in masters_checks if c.severity == "error")
                m_score = ValidationScore.from_validation(m_result)
                report.masters_score = m_score.score if m_score.score < 100 else 100.0

            # ── Step 4: Round-trip validation ───────────────────── #
            rt_result = self.round_trip.validate(invoice, xml_str)
            self._merge_result(report, rt_result, "round_trip")

            # ── Step 5: Tally Simulator ─────────────────────────── #
            vchtype = invoice.voucher_type.value if invoice.voucher_type else ""
            tally_result = self.tally_sim.simulate_import(xml_str, expected_vchtype=vchtype)
            self._merge_result(report, tally_result, "tally")

        # ── Final score ─────────────────────────────────────────── #
        all_checks = acct_result.checks.copy()
        if xml_str:
            all_checks.extend(xml_result.checks)
            all_checks.extend(rt_result.checks)
            all_checks.extend(tally_result.checks)

        combined = ValidationResult()
        combined.checks = all_checks
        combined.passed = all(c.passed for c in all_checks if c.severity == "error")

        final_score = ValidationScore.from_validation(combined)
        report.total_score = final_score.score
        report.passed = final_score.passed
        report.ready_for_tally = final_score.passed and final_score.score >= 80.0

        return report

    def _merge_result(self, report: ValidationReport, result: ValidationResult, category: str):
        """Merge a ValidationResult into the report."""
        for c in result.checks:
            check_dict = {
                "name": c.name or "",
                "passed": c.passed,
                "message": c.message,
                "severity": c.severity,
                "category": c.category or category,
            }
            report.checks.append(check_dict)

            if not c.passed:
                if c.severity == "error":
                    report.errors.append(f"[{c.category or category}] {c.message}")
                elif c.severity == "warning":
                    report.warnings.append(f"[{c.category or category}] {c.message}")

        # Collect blocking errors
        for msg in result.blocking_errors:
            report.blocking_errors.append(msg)
            report.ready_for_tally = False

    def generate_report_only(
        self,
        invoice: StandardizedInvoice,
        xml_str: Optional[str] = None,
    ) -> dict:
        """Convenience: run and return to_dict()."""
        return self.run(invoice, xml_str).to_dict()

    def human_report(
        self,
        invoice: StandardizedInvoice,
        xml_str: Optional[str] = None,
    ) -> str:
        """Convenience: run and return human-readable string."""
        return self.run(invoice, xml_str).to_human_report()
